### ISSUE TITLE
Envio de mensagem para usuárrios cadastrados

### ISSUE THREAD

**Issue by CauanCabral** [CauanCabral/Comitiva#1]
Olhando o sistema hoje, vi que temos 29 inscritos e 54 usuários cadastrados.

Precisamos fazer um esquema no sistema aonde podemos enviar um e-mail para esses dois grupos de usuários.

Para os inscritos, avisando dos sorteios que vamos fazer no evento por exemplo.

Para os usuários não inscritos no evento, avisar que é 15 reais até tal dia e tals.. pra fazer o pessoal se inscrever.

**Comment by felipevr** [comment]
Implementar envio de e-mails para grupos:
–        usuários registrados não inscritos,
–        usuários inscritos que não confirmaram pagamento,
–        usuários que confirmaram pagamento e não fizeram checkin (ausentes)
–        Usuário que participaram do evento (fizeram checkin)
