### ISSUE TITLE
Cadastro de usuário

### ISSUE THREAD

**Issue by felipevr** [CauanCabral/Comitiva#14]
Após o cadastro do usuário, e posterior validação do endereço de e-mail,  a senha cadastrada não funciona.

Para poder acessar o usuário tem que usar o "esqueci a senha" para redefinir a senha e somente após feito isso que conseguirá acessar o sistema.

**Comment by CauanCabral** [comment]
Corrigido em f0dd7534bcb38d83c98f9698bdfa87af0d175e65
