### ISSUE TITLE
Inscrição em Eventos

### ISSUE THREAD

**Issue by felipevr** [CauanCabral/Comitiva#15]
Mostrar a data de encerramento da inscrição ou remover o botão "Inscrever-se" se o evento já tiver acontecido.

**Comment by CauanCabral** [comment]
Isso já existe.

Quando você cria um evento você adiciona as datas que ele ocorrá.

As inscrições são bloqueadas quando o evento estiver para iniciar (mesmo dia).

**Comment by felipevr** [comment]
Certo, tentei e apareceu "A inscrição não pôde ser realizada. O evento não existe ou as inscrições foram encerradas.".
Ok.

Então tem que mostrar as datas dos eventos na listagem de inscrições ou então pelo menos ocultar o botão "Inscrever-se".
