### ISSUE TITLE
Sistema de sorteio

### ISSUE THREAD

**Issue by zehzinho** [CauanCabral/Comitiva#5]
Sortear usuários apenas entre os que fizeram check-in.

**Comment by CauanCabral** [comment]
Anotação feita pelo Felipe em outra issue:

"Fazer um módulo para sorteio de brindes,
onde a cada sorteio irá selecionar uma pessoa entre as que fizeram checkin
e marcará ela como sorteada para não ser sorteada novamente
opcionalmente poderá ser adicionado uma opção de marcar caso a pessoa esteja ausente, ou então adicionar uma observação (por exemplo o item q recebeu).

Armazenando assim as pessoas que foram sorteadas para posterior consulta."
