### ISSUE TITLE
Sistema de sorteio de brindes

### ISSUE THREAD

**Issue by felipevr** [CauanCabral/Comitiva#8]
Fazer um módulo para sorteio de brindes, 

onde a cada sorteio irá selecionar uma pessoa entre as que fizeram checkin
e marcará ela como sorteada para não ser sorteada novamente

opcionalmente poderá ser adicionado uma opção de marcar caso a pessoa esteja ausente, ou então adicionar uma observação (por exemplo o item q recebeu).

Armazenando assim as pessoas que foram sorteadas para posterior consulta.

**Comment by CauanCabral** [comment]
Issue reportada anteriormente pelo zehzinho.
Copiei o conteúdo dessas como comentário na outra.
